apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: argocd
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::386743483719:role/loki-logs2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-loki
  namespace: argocd
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::386743483719:role/loki-logs2


