apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- project.yaml
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.7/manifests/namespace-install.yaml
