apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki
  namespace: grafana-loki
spec:
  project: grafana-loki
  source:
    chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.9.9
    helm:
      releaseName: loki-stack
      valueFiles:
      - values.yaml

  destination:
    server: "https://kubernetes.default.svc"
    namespace: grafana-loki

